[event_gateway]  
    [event_gateway.v1]    
        [event_gateway.v1.sys]      
            [event_gateway.v1.sys.service]        
                disable_frontend_tls = true

## sudo chef-automate config patch disabletls.toml